// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Proteja seu banco de dados e dados do Cloud Storage usando as regras de segurança do Firebase, não restringindo e/ou obscurecendo suas chaves de API.
  // https://firebase.google.com/docs/projects/api-keys
  // https://firebase.google.com/docs/rules

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyM5xCRFthAqQ44_S_y5HWri8Cj3W3Gy0',
    appId: '1:68950089415:android:e02980b06c465f141ca8e2',
    messagingSenderId: '68950089415',
    projectId: 'vf-desafio-capyba',
    storageBucket: 'vf-desafio-capyba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCATd3i9tn5vJJd1Ko_g-0YI3vjfo0TCjA',
    appId: '1:68950089415:ios:9e78d4fa2ce4469b1ca8e2',
    messagingSenderId: '68950089415',
    projectId: 'vf-desafio-capyba',
    storageBucket: 'vf-desafio-capyba.appspot.com',
    iosClientId:
        '68950089415-78suug3244h0mf1rh6fljd3jkl66gjjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioCapyba',
  );
}
